# Generated by Django 5.2.4 on 2025-07-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cantidad_de_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_de_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_de_entrega', models.CharField(help_text='Día de la semana para la entrega', max_length=20)),
                ('importe_a_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
